### ISSUE TITLE
Unclear behaviour in certain situations

### ISSUE THREAD

**Issue by cristian-5** [pwmarcz/kaboom#23]
Let's say I have this situation:

<img width="448" alt="Screenshot 2021-05-21 at 22 09 17" src="https://user-images.githubusercontent.com/30161685/119193021-4e2c3680-ba81-11eb-994d-ace4b2868eda.png">

Is it safe to guess the bottom question marks if I have the possibility of opening the top cell with a question mark or should I open the top one first because I know it's empty?

**Comment by EveryOtherUsernameWasAlreadyTaken** [comment]
Guessing the bottom ones? These don't need guessing. The left bottom question mark is a bomb, the right bottom one is free.

**Comment by pwmarcz** [comment]
Sorry, it looks like I missed this one. @EveryOtherUsernameWasAlreadyTaken is right.

To answer the more general question, the guessing requirement is "global": as long as there are any guaranteed-empty cells on the board, you are not allowed to guess, even if there is an ambiguous situation elsewhere.

That's because it's not easy to prove that these two are independent: revealing the safe cell might lead to resolving the ambiguous situation. Even if there are completely disjoint, sometimes the situation might get resolved because the total number of mines is fixed.
