### ISSUE TITLE
What does adjacent mean, exactly?

### ISSUE THREAD

**Issue by EveryOtherUsernameWasAlreadyTaken** [pwmarcz/kaboom#25]
It seems my last click was not adjacent enough:

![image](https://user-images.githubusercontent.com/5978637/130161528-10518eac-b380-458e-8977-11fb8b008d55.png)

**Comment by pwmarcz** [comment]
Hi,
It means adjacent to one of the revealed tiles. In the screenshot, there were no safe tiles, but you could click one of the tiles marked as yellow: the game would have permitted that as a guess, because these tiles are next to the revealed 5 tile.

Some people find that rule arbitrary. If you would prefer to play without it, click the "Allow guessing anywhere" checkbox. The game will then accept any tile outside of boundary as a guess.

**Comment by EveryOtherUsernameWasAlreadyTaken** [comment]
Okay. I clicked adjacent to a guaranteed bomb. It's fine.
